### ISSUE TITLE
Question about using assert() inside of except.c

### ISSUE THREAD

**Issue by zanyoats** [drh/cii#19]
I am a bit stumped how `Except_raise` implementation can use `assert` when it is implemented in terms of `Except_raise`.
https://github.com/drh/cii/blob/9cb8b5f0a3b634a7459f1788b07d1d2321b8689c/src/except.c#L19

Using gcc I got the following error:
```
except.c: In function ‘Except_raise’:
except.c:11:6: warning: infinite recursion detected [-Winfinite-recursion]
   11 | void Except_raise(const T *e, const char *file, int line)
      |      ^~~~~~~~~~~~
In file included from except.c:3:
./except.h:35:18: note: recursive call
   35 | #define RAISE(e) Except_raise(&(e), __FILE__, __LINE__)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./assert.h:10:33: note: in expansion of macro ‘RAISE’
   10 | #define assert(e) ((void)((e)||(RAISE(Assert_Failed),0)))
      |                                 ^~~~~
except.c:15:3: note: in expansion of macro ‘assert’
   15 |   assert(e);
```

If I use <assert.h> I can resolve this but I am not sure that is what was intended since it won't raise an exception in the way the assert module does.

**Comment by juniskane** [comment]
The warning seems incorrect. There is no infinite recursion as `RAISE()` here always calls `Except_raise()` with `&Assert_Failed`, which is guaranteed to be a non-NULL pointer (address of file scope struct). Therefore the assertion on line 19 of except.c cannot trigger when it is called from `assert()`.
